### ISSUE TITLE
可否添加ep模式的vscode背景图

### ISSUE THREAD

**Issue by xiaoxian521** [element-plus/design-materials#1]
例如，标准尺寸1920*1080
![image](https://user-images.githubusercontent.com/44761321/133740841-092a0916-8939-4e76-a37c-cf3134e1a98d.png)

**Comment by huangzhongzhong** [comment]
已增加。
![Element Plus Vscode 背景图-仅图标](https://user-images.githubusercontent.com/46183365/133891045-c6847e04-61a3-4fdf-9a84-2c95f2a2df49.png)
![Element Plus Vscode 背景图-完整版](https://user-images.githubusercontent.com/46183365/133891052-cfa8c584-a3da-4b64-a4a7-82f07c9c2165.png)
